apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: time-check
  name: time-check
  namespace: datacenter
spec:
  volumes:
  - name: log-volume
    emptyDir: {}
  containers:
  - image: busybox:latest
    name: time-check
    command: ["/bin/sh", "-c"]
    args: ["echo `while true; do date; sleep $TIME_FREQ;done > /opt/security/time/time-check.log`"]
    env:
    - name: TIME_FREQ
      valueFrom:
        configMapKeyRef:
          name: time-config
          key: TIME_FREQ
    volumeMounts:
    - name: log-volume
      mountPath: /opt/security/time
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
