---
- hosts: stapp01
  become: true
  tasks:
    - name: include vars
      include_vars:
        dir: data

    - name: Create groups
      group:
        name: "{{ item }}"
        state: present
      with_items:
        - developers
        - admins
      
    - name: Create users of admins group
      user:
        name: "{{ item }}"
        comment: "{{ item }}"
        password:  "{{ 'TmPcZjtRQx' | password_hash ('sha512') }}"
        create_home: yes
        groups: admins, wheel
      with_items: "{{ admins }}"

    - name: Create users of developers group
      user:
        name: "{{ item }}"
        comment: "{{ item }}"
        password:  "{{ 'B4zNgHA7Ya' | password_hash ('sha512') }}"
        home: "/var/www/{{ item }}"
        create_home: yes
        group: developers
      with_items: "{{ developers }}"
