apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    user nginx;
    worker_processes  1;
    events {
      worker_connections  10240;
    }
    http {
      server {
          listen       8092;
          server_name  localhost;
          location / {
            root   /var/www/html;
            index  index.html index.htm index.php;
        }
      }
    }
