apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: nginx-phpfpm
  name: nginx-service
spec:
  ports:
  - port: 8092
    protocol: TCP
    targetPort: 8092
    nodePort: 30012
  selector:
    run: nginx-phpfpm
  type: NodePort
status:
  loadBalancer: {}
