apiVersion: v1
data:
  password: WVVJaWRoYjY2Nw==
kind: Secret
metadata:
  creationTimestamp: null
  name: mysql-root-pass
---
apiVersion: v1
data:
  username: a29kZWtsb3VkX2FpbQ==
  password: VG1QY1pqdFJReA==
kind: Secret
metadata:
  creationTimestamp: null
  name: mysql-user-pass
---
apiVersion: v1
data:
  database: a29kZWtsb3VkX2RiOQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: mysql-db-url

